cache_type: DBCache
warmup_steps: 0
max_cached_steps: -1
Fn_compute_blocks: 1
Bn_compute_blocks: 0
residual_diff_threshold: 0.12
enable_taylorseer: true
enable_encoder_taylorseer: true
taylorseer_cache_type: residual
taylorseer_kwargs:
  n_derivatives: 2
